version: '3.2'

services:
    mongo:
        image: mongo:4.4.5-bionic
        ports:
            - "27017:27017"
        volumes:
        -   "./db:/data/db"
    server:
        build:
            context: ./server
        depends_on:
            - mongo
        ports:
            - "3000:3000"
        environment:
            - MONGO_DB_HOST=mongo
