name: Docker Image CI Push

on:
  push:
    branches: master

permissions:
  packages: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
        env:
          CR_PAT: ${{ env.CR_PAT }}
      - name: Build the Docker image
        run: |
          cd server
          docker build . -t ghcr.io/intuit/maven-build-scanner-server:latest
      - name: Push the Docker image
        run: docker push ghcr.io/intuit/maven-build-scanner-server:latest
