name: Docker Image CI Push

on:
  push:
    branches: master

permissions:
  packages: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          cd server
          docker build . -t ghcr.io/intuit/maven-build-scanner-server:latest
          docker push ghcr.io/intuit/maven-build-scanner-server:latest
